### ISSUE TITLE
Location of training data

### ISSUE THREAD

**Issue by TonyKess** [mfumagalli/ImaGene#1]
Hello,
I'm working through the binary classification tutorial, but can't find the example training data on the github page. Will this data be added, or is it available elsewhere?

Thanks!

**Comment by mfumagalli** [comment]
you can reproduce the training data with the command: ` bash Reproduce/generate_data.sh Binary` by first changing the script to set up your path and directories.

**Comment by mfumagalli** [comment]
we now provided a more user-friendly script to generate simulations directly from python using msms. Please find instructions on the new tutorial for binary classification. Feedback appreciated.
