### ISSUE TITLE
Fix hardcoded absolute paths in notebook and param files

### ISSUE THREAD

**Issue by mathemage** [mfumagalli/ImaGene#3]
[...] @mfumagalli please don't hardcode absolute paths/names/settings that would work only on your computer.

Specifically, I have to change `/home/mfumagal/...` paths everywhere every time. It is troubling for me and I believe it must be terribly frustrating for non-expert users. I would suggest at least to extract a path variable that can set/changed at the beginning of the notebook.

Notebooks should be **runnable for anyone just as is** and that way they should be provided by us.

_Originally posted by @mathemage in https://github.com/mfumagalli/ImaGene/issues/2#issuecomment-600814872_

**Comment by mathemage** [comment]
![ImaGene_iss_3](https://user-images.githubusercontent.com/3373514/77573215-3df1e900-6ec8-11ea-9ec9-b5dcf703881e.png)

**Comment by mfumagalli** [comment]
I'd rather not accepting this change but keep it as it is so that users can set the paths in the parameters file along all other variables that need to be set.
