### ISSUE TITLE
pymc3.stats.hpd outdated

### ISSUE THREAD

**Issue by GabrielMarengoQM** [mfumagalli/ImaGene#6]
pymc3.stats.hpd is no longer supported and instead az.hdi may be used from the ArviZ package (v0.12).

**Comment by mfumagalli** [comment]
thanks; can you provide the exact replacement of the line using pymc3.stats.hpd or push a request?

**Comment by GabrielMarengoQM** [comment]
I cannot access the repository when pushing.

Here is the replacement (on line 114 of ImaGene.y):
HPD = az.hdi(samples_distr, credible_interval = 0.95)

**Comment by mfumagalli** [comment]
updated
